### ISSUE TITLE
Would you mind to provide the CIFAR-10 model?

### ISSUE THREAD

**Issue by D-X-Y** [chenxi116/PNASNet.pytorch#1]
Would you mind to provide the CIFAR-10 model?
I use the provided architecture https://github.com/chenxi116/PNASNet.pytorch/blob/master/genotypes.py#L5
and the code from https://github.com/quark0/darts/blob/master/cnn/model.py#L111, but obtain the model parameter size of 4.2 MB (I use initial channel of 48 and layers of 11). Is there anything wrong?

**Comment by chenxi116** [comment]
Thanks for the question. The number of layers should be 9, and their code used a different stem structure (between image and first cell) than mine. These are probably the cause of the parameter size mismatch.

**Comment by D-X-Y** [comment]
@chenxi116 Thanks for your information. Would you mind to let me know the stem structure that you use for CIFAR?

**Comment by chenxi116** [comment]
Please see the TensorFlow implementation for reference: https://github.com/tensorflow/models/blob/master/research/slim/nets/nasnet/nasnet.py#L275

**Comment by D-X-Y** [comment]
Thanks a lot. It seems the stem structures for CIFAR are similar (maybe one use the bias term and one not).
