### ISSUE TITLE
Cells not repeated x N at each layer ?? 

### ISSUE THREAD

**Issue by ngBroken** [chenxi116/PNASNet.pytorch#4]
Hi, thanks for posting this code. Maybe I am missing something but it seems that at each layer the cells are not repeated N times as in the PNAS paper?

**Comment by chenxi116** [comment]
See https://github.com/chenxi116/PNASNet.pytorch/blob/master/model.py#L106. Basically the total number of layers is used in the code, so N is implicit.

**Comment by ngBroken** [comment]
thanks for that I misinterpreted, so N is essentially hard-coded at 3?

**Comment by chenxi116** [comment]
I wouldn't say it's hard-coded, since you can easily change the total number of layers at https://github.com/chenxi116/PNASNet.pytorch/blob/master/main.py#L22

**Comment by ngBroken** [comment]
but doesn't this code:
https://github.com/chenxi116/PNASNet.pytorch/blob/master/model.py#L107
make every fourth layer the reduction:?

**Comment by chenxi116** [comment]
No. Why do you think it does? Maybe you want to read https://github.com/chenxi116/PNASNet.pytorch/blob/master/model.py#L107 more carefully?

**Comment by ngBroken** [comment]
okay I see now. Thanks a lot for your help.
